# Docker Compose file for the dev environment.

version: '3.1'

services:
  db:
    image: docker.io/mariadb:lts
    container_name: sharemeister-db
    networks:
      -  "sharemeister"
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true

  phpmyadmin:
    image: docker.io/phpmyadmin:latest
    container_name: sharemeister-phpmyadmin
    networks:
      - "sharemeister"
    ports:
      - 8080:80
    environment:
      - PMA_USER=root
      - UPLOAD_LIMIT=300M

networks:
  sharemeister:
    name: sharemeister
    external: true